version: '3.8'

services:
  masclet-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: masclet-api
    networks:
      - masclet-network

  masclet-frontend-node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: masclet-frontend-node
    networks:
      - masclet-network

  masclet-frontend:
    image: nginx:alpine
    container_name: masclet-frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - masclet-network
    depends_on:
      - masclet-api
      - masclet-frontend-node

networks:
  masclet-network:
    driver: bridge
