version: '3'

services:
  masclet-frontend-node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: masclet-frontend-node:latest
    container_name: masclet-frontend-node
    restart: unless-stopped
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - API_URL=http://masclet-api:8000
    networks:
      - masclet-network

  masclet-frontend:
    image: nginx:latest
    container_name: masclet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - masclet-frontend-node
    networks:
      - masclet-network

networks:
  masclet-network:
    external: true
