http:
  middlewares:
    secure-headers:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    compression:
      compress: {}