services:
  # Servidor Node.js para SSR
  masclet-frontend-node:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: masclet-frontend-node
    restart: unless-stopped
    networks:
      - masclet-network
    # No exponemos el puerto 3000 al exterior, solo internamente para Nginx

  # Nginx como proxy inverso y servidor de estáticos
  masclet-frontend-nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: masclet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - masclet-frontend-node
    networks:
      - masclet-network

networks:
  masclet-network:
    external: true
